export const dataFilial = [
    {
        id: 1,
        filialnameuz: 'Shaxriston',
        filialnameru: 'Shaxriston',
        mark: "Metro ro'parasida",
        worktime_start: '09:00',
        worktime_end: '20:00',
    },
    {
        id: 2,
        filialnameuz: 'Xadra fast-food',
        filialnameru: 'Xadra fast-food',
        mark: "Royson dom oldida",
        worktime_start: '09:00',
        worktime_end: '20:00',
    },
    {
        id: 3,
        filialnameuz: 'Maksim girkiy',
        filialnameru: 'Maksim girkiy',
        mark: "Metro ro'parasida",
        worktime_start: '09:00',
        worktime_end: '20:00',
    },
    {
        id: 4,
        filialnameuz: 'Uz kebab',
        filialnameru: 'Uz kebab',
        mark: "Hamkorbank ro'parasida",
        worktime_start: '09:00',
        worktime_end: '20:00',
    },
    {
        id: 5,
        filialnameuz: 'Sim-sim',
        filialnameru: 'Sim-sim',
        mark: "Aloqa uyi ro'parasida",
        worktime_start: '09:00',
        worktime_end: '20:00',
    },
]