export const dataCustomers = [
    {
        id: 1,
        name: 'Jon Doe',
        phone: '+998 99 900 00 00',
        numberOfBooks: 3,
        status: 'aktiv',
    },
    {
        id: 2,
        name: 'Jak Don',
        phone: '+998 99 900 00 00',
        numberOfBooks: 5,
        status: 'block',
    },
    {
        id: 3,
        name: 'Molly Doe',
        phone: '+998 99 900 00 00',
        numberOfBooks: 1,
        status: 'aktiv',
    },
    {
        id: 4,
        name: 'Akrom Saidov',
        phone: '+998 99 900 00 00',
        numberOfBooks: 2,
        status: 'block',
    },
    {
        id: 5,
        name: 'Salim Karimov',
        phone: '+998 99 900 00 00',
        numberOfBooks: 8,
        status: 'block',
    },
    {
        id: 6,
        name: 'Tohir Muslimov',
        phone: '+998 99 900 00 00',
        numberOfBooks: 4,
        status: 'aktiv',
    },
    {
        id: 7,
        name: 'Sanjar Latipov',
        phone: '+998 99 900 00 00',
        numberOfBooks: 5,
        status: 'aktiv',
    },
    {
        id: 8,
        name: 'Anvar Kozimov',
        phone: '+998 99 900 00 00',
        numberOfBooks: 8,
        status: 'block',
    },
    {
        id: 9,
        name: 'Davron Rustamov',
        phone: '+998 99 900 00 00',
        numberOfBooks: 5,
        status: 'aktiv',
    },
    {
        id: 10,
        name: 'Gress Doe',
        phone: '+998 99 900 00 00',
        numberOfBooks: 1,
        status: 'aktiv',
    },
    {
        id: 11,
        name: 'Jon Doe',
        phone: '+998 99 900 00 00',
        numberOfBooks: 5,
        status: 'block',
    },
]